### ISSUE TITLE
As Ben, I want to be able to write out a vision for each major area of my life so I can be clear about what I want my life to look like

### ISSUE THREAD

**Issue by diva-D** [diva-D/bloc-capstone-project#1]
## TODO
- [ ] Create Vision model
- [ ] Create Vision view
- Index  
  - Shows each area of life with written story and linked outcomes
  - [ ] Have empty "Area" sections
    - Health
    - Wealth
    - Relationships
    - Career
    - Mental
    - Spiritual
  - [ ] Accordion box for user to write out vision for area
    - [ ] Button to save vision description
  - [ ] "+" icon to add outcome(s) to vision area
- [ ] Vision routes
  - [ ] Add
  - [ ] Edit
  - [ ] Update

**Comment by diva-D** [comment]
**Wireframe**
<img width="774" alt="Vision" src="https://user-images.githubusercontent.com/28694272/56074918-19634500-5e0e-11e9-8a9d-7b668995d456.png">
